# Generated by Django 3.2 on 2021-07-10 09:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('phone_no', models.CharField(max_length=10, unique=True)),
                ('email_id', models.EmailField(help_text='this is your user name', max_length=50, unique=True)),
                ('password', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('bill_no', models.AutoField(primary_key=True, serialize=False)),
                ('patient', models.CharField(max_length=50)),
                ('d_o_b', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('disease', models.CharField(max_length=50)),
                ('date_of_adm', models.DateField()),
                ('date_of_dis', models.DateField()),
                ('room_no', models.IntegerField()),
                ('payment_status', models.CharField(default='Pending', max_length=50)),
                ('total_bill', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('head', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('d_o_b', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=100)),
                ('department', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalStore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('buy_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('mfd_date', models.DateField()),
                ('exp_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_no', models.IntegerField()),
                ('room_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('empty', 'Empty'), ('full', 'Full')], default='Empty', max_length=20)),
                ('no_of_bed', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('join_date', models.DateField(help_text='date must be in ( mm/dd/yy ) format')),
                ('salary', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('patient', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.datetime(2021, 7, 10, 15, 22, 34, 188701))),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('d_o_b', models.DateField()),
                ('blood', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('disease', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('room_no', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime(2021, 7, 10, 15, 22, 34, 186707))),
                ('doctor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementapp.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='OrderMedicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('buy_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateField(default=datetime.datetime(2021, 7, 10, 15, 22, 34, 209645))),
                ('payment_status', models.CharField(default='Pending', max_length=50)),
                ('med_name', models.ManyToManyField(default=0, to='HospitalManagementapp.MedicalStore')),
            ],
        ),
    ]
