# Generated by Django 3.2 on 2021-07-10 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermedicine',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 11, 0, 6, 9, 678013)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 11, 0, 6, 9, 662389)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 11, 0, 6, 9, 662389)),
        ),
    ]
